# Generated by Django 4.2.7 on 2024-07-22 17:17

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('availability', '0002_alter_appointmentduration_duration'),
    ]

    operations = [
        migrations.AlterModelOptions(
            name='appointmentduration',
            options={'verbose_name': 'Appointment Duration', 'verbose_name_plural': 'Appointment Durations'},
        ),
        migrations.AlterModelOptions(
            name='availabilityslot',
            options={'ordering': ['day_of_week', 'start_time'], 'verbose_name': 'Availability Slot', 'verbose_name_plural': 'Availability Slots'},
        ),
    ]
