# Generated by Django 4.2.7 on 2024-07-22 17:17

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('budget_manager', '0002_alter_expense_date'),
    ]

    operations = [
        migrations.AlterModelOptions(
            name='expense',
            options={'ordering': ['-date'], 'verbose_name': 'Expense', 'verbose_name_plural': 'Expenses'},
        ),
        migrations.AlterModelOptions(
            name='income',
            options={'ordering': ['-date'], 'verbose_name': 'Income', 'verbose_name_plural': 'Incomes'},
        ),
    ]
