# Generated by Django 4.2.7 on 2024-07-22 19:18

from django.db import migrations, models
import django.db.models.deletion
import django.utils.timezone


class Migration(migrations.Migration):

    dependencies = [
        ('orders', '0015_remove_orderitem_price_alter_orderitem_quantity_and_more'),
        ('budget_manager', '0003_alter_expense_options_alter_income_options'),
    ]

    operations = [
        migrations.CreateModel(
            name='Debt',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('name', models.CharField(max_length=200)),
                ('amount', models.DecimalField(decimal_places=2, max_digits=10)),
                ('date_created', models.DateField(default=django.utils.timezone.now)),
                ('date_paid', models.DateField(blank=True, null=True)),
                ('is_paid', models.BooleanField(default=False)),
                ('order', models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, to='orders.order')),
            ],
            options={
                'verbose_name': 'Debt',
                'verbose_name_plural': 'Debts',
                'ordering': ['-date_created'],
            },
        ),
    ]
