# Generated by Django 4.2.7 on 2024-07-22 19:24

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('budget_manager', '0004_debt'),
    ]

    operations = [
        migrations.AddField(
            model_name='debt',
            name='description',
            field=models.TextField(blank=True),
        ),
        migrations.AddField(
            model_name='debt',
            name='expense',
            field=models.OneToOneField(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='debt', to='budget_manager.expense'),
        ),
        migrations.AddField(
            model_name='debt',
            name='income',
            field=models.OneToOneField(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='debt', to='budget_manager.income'),
        ),
    ]
