# Generated by Django 4.2.7 on 2024-07-22 19:26

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('orders', '0015_remove_orderitem_price_alter_orderitem_quantity_and_more'),
        ('budget_manager', '0005_debt_description_debt_expense_debt_income'),
    ]

    operations = [
        migrations.AlterField(
            model_name='income',
            name='order',
            field=models.OneToOneField(blank=True, null=True, on_delete=django.db.models.deletion.CASCADE, to='orders.order'),
        ),
    ]
