# Generated by Django 4.2.5 on 2024-07-08 23:16

from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='Client',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('telegram_id', models.PositiveIntegerField(unique=True)),
                ('description', models.TextField(blank=True)),
                ('treatment_preferences', models.TextField(blank=True)),
                ('address', models.CharField(blank=True, max_length=200)),
            ],
        ),
    ]
