# Generated by Django 4.2.7 on 2024-07-22 17:17

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('clients', '0001_initial'),
    ]

    operations = [
        migrations.AlterModelOptions(
            name='client',
            options={'ordering': ['telegram_id'], 'verbose_name': 'Client', 'verbose_name_plural': 'Clients'},
        ),
    ]
