# Generated by Django 4.2.7 on 2024-07-22 16:04

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('orders', '0015_remove_orderitem_price_alter_orderitem_quantity_and_more'),
        ('partners', '0001_initial'),
    ]

    operations = [
        migrations.AlterUniqueTogether(
            name='partnerorder',
            unique_together={('partner', 'order')},
        ),
    ]
