# Generated by Django 4.2.7 on 2024-07-22 17:17

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('inventory', '0003_alter_product_options'),
    ]

    operations = [
        migrations.AlterModelOptions(
            name='pricehistory',
            options={'ordering': ['-date'], 'verbose_name_plural': 'Price Histories'},
        ),
    ]
