# Generated by Django 4.2.5 on 2024-07-06 23:33

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('orders', '0002_alter_order_status'),
    ]

    operations = [
        migrations.AddField(
            model_name='order',
            name='meeting_time',
            field=models.DateTimeField(blank=True, null=True),
        ),
    ]
