# Generated by Django 4.2.5 on 2024-07-07 00:16

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('orders', '0004_alter_order_status'),
    ]

    operations = [
        migrations.AlterField(
            model_name='order',
            name='telegram_order_id',
            field=models.IntegerField(),
        ),
    ]
