# Generated by Django 4.2.5 on 2024-07-09 19:00

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('orders', '0007_alter_order_id'),
    ]

    operations = [
        migrations.RenameField(
            model_name='order',
            old_name='telegram_order_id',
            new_name='telegram_user_id',
        ),
    ]
