# Generated by Django 4.2.7 on 2024-07-21 20:19

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('orders', '0008_rename_telegram_order_id_order_telegram_user_id'),
    ]

    operations = [
        migrations.RenameField(
            model_name='orderitem',
            old_name='price',
            new_name='selling_price',
        ),
    ]
