# Generated by Django 4.2.7 on 2024-07-21 20:23

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('orders', '0009_rename_price_orderitem_selling_price'),
    ]

    operations = [
        migrations.AlterField(
            model_name='order',
            name='telegram_user_id',
            field=models.IntegerField(blank=True, null=True),
        ),
    ]
