# Generated by Django 4.2.7 on 2024-07-21 20:34

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('orders', '0011_alter_order_profit_alter_order_total_price'),
    ]

    operations = [
        migrations.AlterField(
            model_name='order',
            name='telegram_user_id',
            field=models.IntegerField(default=-1),
            preserve_default=False,
        ),
    ]
